version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=HotelManagement;User=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;
    networks:
      - hotel-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
    ports:
      - "1433:1433"
    volumes:
      - hotel-db-data:/var/opt/mssql
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge

volumes:
  hotel-db-data:
