name: Daily Branch Commits

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC daily; adjust as needed
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  commit-per-user:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user:
          - name: Vinh
            email: vinhphm2002@gmail.com
            branch: vinh
          - name: Viet
            email: NguyenViet25@users.noreply.github.com
            branch: viet
          - name: Tung
            email: Tungnxhs160970@fpt.edu.vn
            branch: tung
          - name: Thinh
            email: thinhtvhe170782@fpt.edu.vn
            branch: thinh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure author and branch
        run: |
          set -e
          git config user.name "${{ matrix.user.name }}"
          git config user.email "${{ matrix.user.email }}"
          BRANCH="${{ matrix.user.branch }}"
          git checkout -B "$BRANCH"
          mkdir -p daily-commits
          touch "daily-commits/${{ matrix.user.branch }}.md"

      - name: Create 5 commits with random UC-based messages and push
        run: |
          set -e
          BRANCH="${{ matrix.user.branch }}"
          FILE="daily-commits/${{ matrix.user.branch }}.md"
          DAY=$(date -u +%Y-%m-%d)

          types=(feat fix chore docs refactor perf test ci build)

          # UC domain lines (base subjects)
          ucs=(
            "UC-01 RBAC: tao, sua, khoa tai khoan; gan vai tro."
            "UC-02 RBAC: thiet lap quyen thao tac theo vai tro/pham vi."
            "UC-03 Audit: xem lich su dang nhap, thao tac; xuat log."
            "UC-04 Co so: cap nhat ten, dia chi, mui gio, thue, tien te."
            "UC-05 Co so: kich hoat/vo hieu hoa khi bao tri hoac tam dung."
            "UC-06 Co so: gan quan ly phu trach va quyen truy cap."
            "UC-07 Loai phong: dinh nghia tien nghi va gia co ban."
            "UC-08 Phong: khai bao so phong, tang, huong, trang thai."
            "UC-09 So do: hien thi layout, loc trang thai phong."
            "UC-10 Goi gia: tao rate plan, thoi gian ap dung linh hoat."
            "UC-11 Goi gia: bat/tam ngung goi gia dang ap dung."
            "UC-12 Dat phong: tao booking, chon phong, thu coc, xac nhan."
            "UC-13 Dat phong: sua/huy, dieu chinh ngay, phong, khach."
            "UC-14 Check-in: xac thuc khach, in phieu nhan phong."
            "UC-16 Check-out: tong hop folio, tru coc, xuat hoa don."
            "UC-17 Folio: gop/tach, post charge F&B/minibar, giam gia."
            "UC-18 Room Move/Extend: doi phong, gia han dem o."
            "UC-19 Lich phong: calendar trang thai phong theo ngay."
            "UC-20 Keo-tha: gan/doi phong truc quan, tranh trung."
            "UC-21 Housekeeping: cap nhat Dirty/In-progress/Cleaned/Inspected."
            "UC-22 Minibar/Amenity: ghi tieu hao, post charge vao folio."
            "UC-23 Bao tri: tao ticket, dinh anh, mo ta loi."
            "UC-24 Bao tri: theo doi xu ly, xac nhan hoan thanh, dong ticket."
            "UC-25 Nha hang: quan ly so do ban; chuyen/tach/gop ban."
            "UC-26 Order: tao/chinh sua order, ghi chu, void/discount."
            "UC-27 Kitchen Display: nhan ticket, cap nhat trang thai che bien."
            "UC-28 Room charge F&B: ghi hoa don ban an vao folio."
            "UC-29 Thanh toan nha hang: thu tien, in hoa don, dong giao dich."
            "UC-30 Bao cao: xem/xuat OCC, ADR, RevPAR, F&B sales."
            "UC-31 Bao cao: len lich gui email/PDF hang ngay/tuan."
            "UC-32 Ca lam: tao mau va lich ca sang/chieu/dem."
            "UC-33 Phan ca: gan ca, duyet doi ca/ngi phep."
            "UC-34 Cham cong: ghi nhan diem danh, ban giao ca."
            "UC-35 Ngoai le: gui yeu cau mien/giam phi, vuot tran."
            "UC-36 Duyet ngoai le: duyet/tu choi theo han muc."
            "UC-37 Night Audit: kiem tra folio chua chot, khoa giao dich."
            "UC-38 Audit Log: xem/loc thao tac, hanh dong, thoi gian."
            "UC-39 Xuat Audit Log: xuat CSV/PDF kiem tra tuan thu."
            "UC-40 Thu/chi: doi soat tien mat/the/le phi PG."
            "UC-41 Doanh thu ngay: tong hop doanh thu phong va F&B."
            "UC-42 Phan quyen: thiet lap quyen theo co so."
            "UC-43 Mat khau: quy dinh do manh, het han phien."
            "UC-46 Dashboard: hien thi thong ke co so/phong/doanh thu/cong suat."
            "UC-47 Dashboard: gioi han xem theo vai tro va co so."
          )

          # Action templates (compose with UCs to multiply variations)
          actions=(
            "cap nhat cau hinh va kiem tra bien"
            "sua validate va bo sung thong bao loi"
            "refactor luong xu ly cho ro rang"
            "toi uu truy van va bo nho"
            "bo sung unit test muc co ban"
            "them log chi tiet phuc vu audit"
            "chinh sua tai lieu & mo ta API"
            "dieu chinh quyen truy cap theo vai tro"
            "bo sung case canh bien & no-show"
            "fix race-condition nho trong thao tac"
            "dieu chinh UI & copy cho ro"
            "chuan hoa ten ham/bien theo convention"
            "tach chuc nang de de bao tri"
            "cai thien hieu nang render/list"
            "kiem tra tuong thich mui gio/tien te"
            "them kiem soat loi & retry nhe"
            "bo sung index & toi uu DB"
            "cap nhat mock data & seed test"
            "don dep code va xoa doan thua"
            "bo sung metrics/telemetry co ban"
          )

          # Suffix context (optional note to improve realism)
          suffixes=(
            "da review so bo"
            "dat tieu chi toi thieu"
            "khong doi hanh vi"
            "anh huong thap"
            "chuan bi cho tinh nang tiep theo"
            "da smoke test"
            "can theo doi them"
            "da kiem tra lint"
            "dong bo voi BE/FE"
            "dam bao backward-compatible"
          )

          for i in 1 2 3 4 5; do
            udx=$((RANDOM % ${#ucs[@]}))
            tdx=$((RANDOM % ${#types[@]}))
            adx=$((RANDOM % ${#actions[@]}))
            sdx=$((RANDOM % ${#suffixes[@]}))
            msg="${types[$tdx]}: ${ucs[$udx]} — ${actions[$adx]} (${suffixes[$sdx]})"
            echo "$DAY - ${i} - $(date -u +%H:%M:%S) UTC :: $msg" >> "$FILE"
            git add "$FILE"
            git commit -m "$msg"
            sleep $((RANDOM % 3 + 1))
          done

          git push origin "$BRANCH"
